name: Render proposal with Nix and Quarto

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        logger: pretty
        log-directives: nix_installer=trace
        backtrace: full
        
    - uses: cachix/cachix-action@v15
      with:
        name: rstats-on-nix
        authToken: '${{ secrets.CACHIX_AUTH }}'

    - name: Build development environment
      run: |
        nix-build

    - name: Render
      run: nix-shell --run "quarto render isc-proposal.qmd"

    - name: Push rendered PDF to main
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    
        # remove old PDF folder and recreate
        rm -rf rendered_proposal
        mkdir -p rendered_proposal
    
        # verify PDF exists
        if [ ! -f isc-proposal.pdf ]; then
          echo "ERROR: isc-proposal.pdf not found"
          exit 1
        fi
    
        # copy PDF into folder
        cp isc-proposal.pdf rendered_proposal/
    
        # ensure Git tracks it
        git add -f rendered_proposal/isc-proposal.pdf
    
        # commit only if changed, skip otherwise
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update rendered proposal"
          git push --force origin main
        fi